/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com", pathname: "/**" },
      { protocol: "https", hostname: "images.pexels.com",   pathname: "/**" },
      { protocol: "https", hostname: "*.supabase.co",       pathname: "/**" },
      { protocol: "https", hostname: "essorqboloappvfwjcbh.supabase.co",       pathname: "/**" },
      { protocol: "https", hostname: "picsum.photos",       pathname: "/**" },
      { protocol: "https", hostname: "techcrunch.com",   pathname: "/**" },
      { protocol: "https", hostname: "*.techcrunch.com",  pathname: "/**" },
      { protocol: "https", hostname: "cdn.collider.com",   pathname: "/**" },
      { protocol: "https", hostname: "*.cdn.collider.com", pathname: "/**" },
      { protocol: "https", hostname: "a57.foxnews.com",    pathname: "/**" },
      { protocol: "https", hostname: "ichef.bbci.co.uk",   pathname: "/**" },
      { protocol: "https", hostname: "*.bbcimg.co.uk",    pathname: "/**" },
      { protocol: "https", hostname: "*.wired.com",        pathname: "/**" },
      { protocol: "https", hostname: "cdn.mosonline.com",   pathname: "/**" },
      { protocol: "https", hostname: "o.aolcdn.com",       pathname: "/**" },
      { protocol: "https", hostname: "*.akamaized.net",      pathname: "/**" },
      { protocol: "https", hostname: "*.theverge.com",      pathname: "/**" },
      { protocol: "https", hostname: "cdn.vox-cdn.com",    pathname: "/**" },
      { protocol: "https", hostname: "*.arstechnica.com",   pathname: "/**" },
      { protocol: "https", hostname: "*.cdn.arstechnica.com", pathname: "/**" },
      { protocol: "https", hostname: "*.mittechreview.com", pathname: "/**" },
      { protocol: "https", hostname: "*.technologyreview.com", pathname: "/**" },
      { protocol: "https", hostname: "*.newsweek.com",      pathname: "/**" },
      { protocol: "https", hostname: "*.forbes.com",        pathname: "/**" },
      { protocol: "https", hostname: "*.cnet.com",         pathname: "/**" },
      { protocol: "https", hostname: "*.engadget.com",       pathname: "/**" },
      { protocol: "https", hostname: "*.digitaltrends.com", pathname: "/**" },
      { protocol: "https", hostname: "*.pcmag.com",       pathname: "/**" },
      { protocol: "https", hostname: "*.zdnet.com",       pathname: "/**" },
      { protocol: "https", hostname: "*.reuters.com",      pathname: "/**" },
      { protocol: "https", hostname: "*.cnn.com",        pathname: "/**" },
      { protocol: "https", hostname: "*.bbc.com",         pathname: "/**" },
      { protocol: "https", hostname: "*.nytimes.com",    pathname: "/**" },
      { protocol: "https", hostname: "*.newsapi.org",      pathname: "/**" },
      { protocol: "https", hostname: "res.cloudinary.com",   pathname: "/**" },
      { protocol: "https", hostname: "*.cloudinary.com",   pathname: "/**" },
    ],
  },
};

export default nextConfig;
